dex:
  config:
    issuer: https://dex.fluffysystems.net
    storage:
      type: kubernetes
      config:
        inCluster: true
    oauth2:
      skipApprovalScreen: true
    connectors:
      - type: oidc
        id: kanidm
        name: Kanidm
        config:
          clientID: $KANIDM_CLIENT_ID
          clientSecret: $KANIDM_CLIENT_SECRET
          redirectURI: https://dex.fluffysystems.net/callback
          issuer: https://auth.fluffysystems.net/oauth2/openid/dex
          # TODO https://github.com/dexidp/dex/pull/3188
          # enablePKCE: true
          scopes:
            - openid
            - profile
            - email
            - groups
    staticClients:
      - id: grafana-sso
        name: Grafana
        redirectURIs:
          - 'https://grafana.fluffysystems.net/login/generic_oauth'
        secretEnv: GRAFANA_SSO_CLIENT_SECRET
      - id: gitea
        name: Gitea
        redirectURIs:
          - 'https://git.fluffysystems.net/user/oauth2/Dex/callback'
        secretEnv: GITEA_CLIENT_SECRET
  envFrom:
    - secretRef:
        name: dex-secrets
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: &host dex.fluffysystems.net
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: dex-tls-certificate
        hosts:
          - *host
